open! Core_kernel

let () = Lwt.async_exception_hook := (fun ex ->
    let open Lwt in
    Lwt_io.eprintlf "üíÄ UNCAUGHT EXCEPTION: %s" (Libutils.Exception.human ex)
    >>= (fun () -> exit 2)
    |> ignore
  )
let main () =
  Liboscn.Scraper.scrape ~last_name:"Johnson" ~first_name:"Bobby" ()

let () =
  Lwt_main.run (
    try%lwt
      main ()
    with
    | (Failure _ as ex) | (Unix.Unix_error _ as ex) | (Exn.Reraised _ as ex) ->
      let message = Libutils.Exception.human ex in
      let%lwt () = Lwt_io.eprintlf "‚ùå An error occured:\n%s" message in
      exit 1
  )
